const express=require('express');const adminAuth=require('../middleware/adminAuth');const ClassSession=require('../models/mongo/ClassSession');const ClassRegistration=require('../models/mongo/ClassRegistration');const router=express.Router();router.use(adminAuth);router.use(require('../middleware/adminInputValidation'));router.param('id',(req,res,next,id)=>/^[a-f\d]{24}$/i.test(id)?next():res.status(404).send('Record not found.')); const clean=v=>String(v||'').trim();const slugify=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function indiaTime(value){const text=clean(value);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(text))return new Date(NaN);const date=new Date(text+':00+05:30');if(!Number.isFinite(date.valueOf()) || new Date(date.getTime()+330*60000).toISOString().slice(0,16)!==text)return new Date(NaN);return date;}
function payload(b){return{title:clean(b.title),slug:clean(b.slug)||slugify(b.title),type:clean(b.type),description:clean(b.description),short_description:clean(b.short_description),instructor_name:clean(b.instructor_name),banner_image:clean(b.banner_image),starts_at:indiaTime(b.starts_at),ends_at:indiaTime(b.ends_at),duration:clean(b.duration),mode:'Online',meeting_platform:clean(b.meeting_platform),meeting_link:clean(b.meeting_link),participant_receives:clean(b.participant_receives),promotional_title:clean(b.promotional_title),promotional_text:clean(b.promotional_text),promotional_url:clean(b.promotional_url),linkedin_post_url:clean(b.linkedin_post_url),price:Math.max(0,Number(b.price)||0),is_free:false,max_seats:Math.max(0,Number(b.max_seats)||0),status:clean(b.status),registration_open:b.registration_open==='on',published:b.published==='on'}}
router.get('/',async(req,res,next)=>{try{res.render('admin/classes',{title:'Webinars & Courses',sessions:await ClassSession.find().sort({starts_at:-1}).lean(),message:req.query.message||''})}catch(e){next(e)}});
router.get('/new',(req,res)=>res.render('admin/class_form',{title:'Create New Course',session:null,error:''}));
router.post('/',async(req,res,next)=>{try{const data=payload(req.body);if(!data.title||!data.type||Number.isNaN(data.starts_at.valueOf())||Number.isNaN(data.ends_at.valueOf())||data.ends_at<=data.starts_at)return res.status(400).render('admin/class_form',{title:'Create New Course',session:req.body,error:'Enter a title, type and valid start/end times.'});await ClassSession.create(data);res.redirect('/admin/classes?message=Course created and ready for publishing controls')}catch(e){next(e)}});
router.get('/:id/edit',async(req,res,next)=>{try{const session=await ClassSession.findById(req.params.id).select('+meeting_link').lean();if(!session)return res.sendStatus(404);res.render('admin/class_form',{title:'Edit Session',session,error:''})}catch(e){next(e)}});
router.post('/:id/edit',async(req,res,next)=>{try{const data=payload(req.body);if(!data.title || !data.type || !Number.isFinite(data.starts_at.valueOf()) || !Number.isFinite(data.ends_at.valueOf()) || data.ends_at<=data.starts_at)return res.status(400).send('Enter a title, type and valid start/end times.');const saved=await ClassSession.findByIdAndUpdate(req.params.id,data,{runValidators:true});if(!saved)return res.sendStatus(404);res.redirect('/admin/classes?message=Session updated')}catch(e){next(e)}});
router.post('/:id/cancel',async(req,res,next)=>{try{await ClassSession.findByIdAndUpdate(req.params.id,{status:'Cancelled',registration_open:false});res.redirect('/admin/classes?message=Session cancelled')}catch(e){next(e)}});
router.get('/:id/registrations',async(req,res,next)=>{try{const session=await ClassSession.findById(req.params.id).lean();if(!session)return res.sendStatus(404);const registrations=await ClassRegistration.find({session_id:session._id}).sort({createdAt:-1}).lean();const totals={total:registrations.length,paid:registrations.filter(r=>r.payment_status==='paid').length,pending:registrations.filter(r=>r.payment_status!=='paid').length,revenue:registrations.filter(r=>r.payment_status==='paid').reduce((sum,r)=>sum+Number(r.amount||0),0)};res.render('admin/class_registrations',{title:'Course Registrations',session,registrations,totals})}catch(e){next(e)}});module.exports=router;
