const assert=require('node:assert/strict');
module.exports=async({models,request,input,gatewayOrders})=>{
  const {Product,Lead,FeatureSettings,DeliverySettings,Pincode,SiteSettings}=models;
  const setup=require('../services/launchSetup');
  const first=await setup.prepare();assert.equal(first.active,false);
  assert.equal((await request('/product/basic-shirt-pattern')).status,404);
  await Product.updateOne({_id:first.product_id},{$set:{base_price:300,physical_price:120,size_information:'Test sizes only',file_formats:'Test PDF',download_information:'Test manual fulfilment',active:true}});
  const before=JSON.stringify(await Product.findById(first.product_id).lean());await setup.prepare();assert.equal(JSON.stringify(await Product.findById(first.product_id).lean()),before,'Setup preserves product');
  let page=await request('/product/basic-shirt-pattern');assert.equal(page.status,200);assert.equal((page.html.match(/<h1\b/g)||[]).length,1);
  assert.match(page.html,/Test sizes only/);assert.match(page.html,/Test PDF/);assert.match(page.html,/garmentdesignstudiocad@gmail.com/);assert.match(page.html,/https:\/\/wa.me\/919791753067/);
  assert.match(page.html,/rel="canonical" href="https:\/\/studio.example.test\/product\/basic-shirt-pattern"/);
  const structured=[...page.html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map(m=>JSON.parse(m[1]));assert.ok(structured.some(x=>x['@type']==='Product' && x.offers.price==='300.00'));
  assert.ok(!page.html.includes('Buy on Amazon'));
  await Product.updateOne({_id:first.product_id},{$set:{amazon_listing_url:'https://www.amazon.in/dp/TEST'}});assert.match((await request('/product/basic-shirt-pattern')).html,/Buy on Amazon/);
  assert.equal((await request('/admin/products/'+first.product_id+'/edit',{amazon_listing_url:'javascript:alert(1)'},'admin')).status,400);
  const digitalInput={...input,items:[{product_id:first.product_id,quantity:1,selected_files:[],selected_addons:[]}]};
  assert.equal((await request('/cart/add',{product_id:first.product_id,quantity:1},'basic-digital')).status,200);
  assert.equal((await request('/checkout',digitalInput,'basic-digital')).status,200);
  const digitalOrder=JSON.parse((await request('/checkout/payment-method/proceed',{},'basic-digital')).html);assert.equal(digitalOrder.delivery_charge,undefined);assert.equal(digitalOrder.subtotal,300);
  const countsBefore=await models.Order.countDocuments(),gatewayBefore=gatewayOrders.length;
  page=await request('/classes/enquiry',undefined,'enquirer');assert.equal(page.status,200);
  const csrf=page.html.match(/name="_csrf" value="([a-f0-9]+)"/)[1];
  const details={_csrf:csrf,name:'Launch Enquirer',whatsapp:'+919876543210',email:'launch@example.test',location:'Chennai',interested_course:'Shirt Pattern Making',experience:'Beginner',preferred_timing:'Evenings IST',message:'Please share the next available class.'};
  assert.equal((await request('/classes/enquiry',{...details,_csrf:'bad'},'enquirer')).status,403);
  const bad=await request('/classes/enquiry',{...details,email:'invalid'},'enquirer');assert.equal(bad.status,400);assert.match(bad.html,/Launch Enquirer/);
  assert.equal((await request('/classes/enquiry',details,'enquirer')).location,'/classes/enquiry/thank-you');
  const lead=await Lead.findOne({email:details.email});assert.equal(lead.interest,'Online Classes');assert.equal(lead.status,'New');assert.equal(lead.interested_course,details.interested_course);
  const admin=await request('/admin/leads?interest=Online%20Classes&interested_course=Shirt%20Pattern%20Making&q=Launch',undefined,'admin');assert.equal(admin.status,200);assert.match(admin.html,/Launch Enquirer/);
  const detail=await request('/admin/leads/'+lead._id,undefined,'admin'),adminCsrf=detail.html.match(/name="_csrf" value="([a-f0-9]+)"/)[1];
  assert.equal((await request('/admin/leads/'+lead._id+'/status',{_csrf:adminCsrf,status:'Contacted'},'admin')).status,303);assert.equal((await Lead.findById(lead._id)).status,'Contacted');
  assert.equal(await models.Order.countDocuments(),countsBefore);assert.equal(gatewayOrders.length,gatewayBefore,'Enquiry never calls gateway');
  await Pincode.create({pincode:'600*',region_id:'south',active:true});
  await models.Courier.create({_id:'launch-courier',name:'Launch Courier',active:true,region_ids:['south'],pincodes:['600*']});
  await models.DeliveryZone.updateOne({_id:'south'},{$addToSet:{partner_ids:'launch-courier'}});
  const checkout=await request('/checkout',{...input,items:[{product_id:first.product_id,quantity:1,physical_quantity:1,selected_files:[],selected_addons:[]}],shipping:{...input.shipping,pincode:'600123',courier_id:'launch-courier'},delivery_charge:999,grand_total:1},'launch-checkout');assert.equal(checkout.status,200);const proceed=await request('/checkout/payment-method/proceed',{},'launch-checkout');assert.equal(proceed.status,200,proceed.html);assert.equal(JSON.parse(proceed.html).delivery_charge,undefined,'Server returns no delivery price');
  for(const url of ['/products','/courses','/contact']){const r=await request(url);assert.equal(r.status,200);assert.match(r.html,/<meta name="description"/);assert.match(r.html,/rel="canonical"/);assert.equal((r.html.match(/<h1\b/g)||[]).length,1);}
  assert.match((await request('/robots.txt')).html,/Sitemap: https:\/\/studio.example.test\/sitemap.xml/);
  assert.match((await request('/sitemap.xml')).html,/\/product\/basic-shirt-pattern/);
  await FeatureSettings.updateOne({_id:'default'},{$set:{patterns_enabled:false,online_classes_enabled:false}},{upsert:true});
  for(const url of ['/products','/product/basic-shirt-pattern','/classes','/classes/enquiry'])assert.equal((await request(url)).status,404);
  const hidden=await request('/sitemap.xml');assert.equal(hidden.status,200);assert.ok(!hidden.html.includes('/product/'));assert.ok(!hidden.html.includes('/classes'));
  assert.equal((await request('/admin/products',undefined,'admin')).status,200);
  await FeatureSettings.updateOne({_id:'default'},{$set:{patterns_enabled:true,online_classes_enabled:true}});
  assert.equal((await request('/product/basic-shirt-pattern')).status,200);
  const keywords=require('../data/seo-keywords.json');assert.equal(keywords.length,1000);assert.equal(new Set(keywords.map(x=>x.keyword)).size,1000);assert.equal(new Set(keywords.map(x=>x.cluster)).size,20);
  assert.equal((await request('/admin/seo')).status,302);assert.equal((await request('/admin/seo/keywords.csv',undefined,'admin')).status,200);
  const saved=process.env.SITE_URL;process.env.SITE_URL='https://temporary.trycloudflare.com';assert.equal(require('../services/seoService').siteOrigin(),'');assert.equal((await request('/sitemap.xml')).status,503);process.env.SITE_URL=saved;
  assert.equal((await SiteSettings.findOne({key:'default'})).contact_email,'garmentdesignstudiocad@gmail.com');
  console.log('PASS: launch draft preservation, product SEO/JSON-LD/contact/Amazon, free class enquiries and admin filters/status, configured dispatch routing, server totals, robots/sitemap visibility and 1,000 keyword ideas.');
};
